### ISSUE TITLE
Switch to a Spring Boot standalone application with runnable fat JAR

### ISSUE THREAD

**Issue by tkrille** [osiam/resource-server#43]
This is the umbrella issue for the transition of this component to a Spring Boot standalone application with an executable fat JAR. See also osiam/osiam#5 for the initial reasons and discussion.

Tasks that have to be done:
- [x] Change Hibernate naming strategy (#11)
- [x] Switch from XML to Java configuration (Issue: #20 / PR: #50)
- [x] Introduce Spring Boot, but keep WAR deployment (#21 / PR: #53)
- [ ] Switch to YAML configration (#44)
- [ ] Switch to standalone application (#45)

Please, maintain this list, if you add new issues or close existing ones.

**Comment by dacrome** [comment]
Moved to https://github.com/osiam/osiam/issues/69
